using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_TEXT_DIRECTION_KIND
{
    COREWEBVIEW2_TEXT_DIRECTION_KIND_DEFAULT,
    COREWEBVIEW2_TEXT_DIRECTION_KIND_LEFT_TO_RIGHT,
    COREWEBVIEW2_TEXT_DIRECTION_KIND_RIGHT_TO_LEFT
}
