using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_FRAME_KIND
{
    COREWEBVIEW2_FRAME_KIND_UNKNOWN,
    COREWEBVIEW2_FRAME_KIND_MAIN_FRAME,
    COREWEBVIEW2_FRAME_KIND_IFRAME,
    COREWEBVIEW2_FRAME_KIND_EMBED,
    COREWEBVIEW2_FRAME_KIND_OBJECT
}
